image: node:latest

stages:
  - build
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - mkdir -p ~/.ssh
  - echo "$bereza_private_key" > ./key
  - chmod 700 ./key
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - ./dist
  script:
    - mkdir /stage
    - PORT=$STAGE_PORT npx nest build
    - cp -r ./dist/* /stage
    - cd .. && ls -la
    - cp package*.json /stage

deploy-stage:
    stage: deploy
    dependencies:
      - build
    only:
    - /stage/
    script:
    - ssh -p 2222 -i ./key gitlab@berezadev.com "cd $STAGE_BACKEND_PATH && npm ci --prefer-offline"
